version: '3.8'

services:
  my-testing-app:
    build: .
    ports:
      - "1000:5000"
    environment:
      FLASK_APP: /app/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    volumes:
      - .:/app
